######################################################################
# Automatically generated by qmake (3.0) Sun Feb 18 17:00:40 2018
######################################################################

QT+=widgets
QT+=gui
TEMPLATE = app
TARGET = points
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cc mainwindow.cc
